language: java

env:
  global:
  - MAVEN_OPTS="-Drevision=$(git describe --dirty --tags)-SNAPSHOT"

stages:
- build
- name: publish
# if: branch = master AND NOT type = pull_request
  
jobs:
  include:
    - stage: build
      jdk: oraclejdk8
      script: mvn -B verify
    - jdk: oraclejdk9
      script: mvn -B verify
    - jdk: openjdk8
      script: mvn -B verify
    - stage: publish
      jdk: openjdk8
      script: travis_wait "cp etc/settings.xml $HOME/.m2/settings.xml && mvn site -B -P snapshot"